const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('browserAPI', {
  onState: (callback) => ipcRenderer.on('browser:state', (_event, state) => callback(state)),
  navigate: (value) => ipcRenderer.send('browser:navigate', value),
  newTab: () => ipcRenderer.send('browser:new-tab'),
  activateTab: (id) => ipcRenderer.send('browser:activate-tab', id),
  closeTab: (id) => ipcRenderer.send('browser:close-tab', id),
  back: () => ipcRenderer.send('browser:back'),
  forward: () => ipcRenderer.send('browser:forward'),
  reload: () => ipcRenderer.send('browser:reload'),
  toggleTile: (selectedIds) => ipcRenderer.send('browser:toggle-tile', selectedIds),
  setTileSelection: (selectedIds) => ipcRenderer.send('browser:set-tile-selection', selectedIds),
  setOverlayWidth: (width) => ipcRenderer.send('browser:set-overlay-width', width),
  updateOverlayData: (data) => ipcRenderer.send('browser:update-overlay-data', data),
  toggleOverlay: (kind, data) => ipcRenderer.send('browser:toggle-overlay', kind, data),
  closeOverlay: () => ipcRenderer.send('browser:close-overlay'),
  overlayAction: (action) => ipcRenderer.send('browser:overlay-action', action),
  onOverlayShow: (callback) => ipcRenderer.on('overlay:show', (_event, kind) => callback(kind)),
  onOverlayExtensions: (callback) => ipcRenderer.on('overlay:extensions', (_event, extensions) => callback(extensions)),
  listExtensions: () => ipcRenderer.invoke('extensions:list'),
  installExtension: (url) => ipcRenderer.invoke('extensions:install', url),
  toggleExtension: (id) => ipcRenderer.invoke('extensions:toggle', id),
  removeExtension: (id) => ipcRenderer.invoke('extensions:remove', id),
  openExtensionOptions: (id) => ipcRenderer.invoke('extensions:options', id),
  toggleDevTools: () => ipcRenderer.send('browser:toggle-devtools'),
  minimize: () => ipcRenderer.send('window:minimize'),
  maximize: () => ipcRenderer.send('window:maximize'),
  close: () => ipcRenderer.send('window:close'),
  clearCookies: (id) => ipcRenderer.invoke('browser:clear-cookies', id),
  clearAllCookies: () => ipcRenderer.invoke('browser:clear-all-cookies'),
  openSettings: () => ipcRenderer.invoke('browser:open-settings')
});
